export const projectsData = [
  {
    id: 1,
    title: 'Preview Anything',
    category: 'Tools',
    description: 'Zero-config CLI that auto-detects and previews JavaScript projects — supports Next.js, Vite, CRA, Express, and static HTML with intelligent port allocation.',
    techStack: ['TypeScript', 'Node.js', 'CLI'],
    link: 'https://github.com/HimanshuMahto/Preveiw-Anything',
    demoLink: null,
  },
  {
    id: 2,
    title: 'Multiple Disease Predictor',
    category: 'ML',
    description: 'Fine-tuned ResNet101V2 on chest X-ray dataset achieving 87.5% accuracy. Integrated into an Android prototype via Flask REST API for real-time disease screening.',
    techStack: ['Python', 'TensorFlow', 'Flask', 'Android'],
    link: 'https://github.com/HimanshuMahto',
    demoLink: null,
  },
  {
    id: 3,
    title: 'Spendify',
    category: 'Android',
    description: 'Full-featured expense tracker with category-based tracking, monthly summaries, and MPAndroidChart visualizations. Room DB with background threads for zero UI blocking.',
    techStack: ['Java', 'Android', 'Room DB', 'MPAndroidChart'],
    link: 'https://github.com/HimanshuMahto/Spendify',
    demoLink: null,
  },
  {
    id: 4,
    title: 'Kuikku',
    category: 'Tools',
    description: 'Privacy-first Chrome extension for quick note-taking and bookmarking. All data stored locally with real-time search — no server, no tracking.',
    techStack: ['JavaScript', 'Chrome API', 'HTML'],
    link: 'https://github.com/HimanshuMahto/Kuikku',
    demoLink: null,
  },
  {
    id: 5,
    title: 'Focus Nest',
    category: 'Android',
    description: 'Productivity app built with Kotlin to help users manage focus sessions, track goals, and stay organized throughout the day.',
    techStack: ['Kotlin', 'Jetpack Compose', 'Android SDK'],
    link: 'https://github.com/HimanshuMahto/Focus-Nest',
    demoLink: null,
  },
  {
    id: 6,
    title: 'Portfolio',
    category: 'Front-End',
    description: 'This site — built with React and Vite. Terminal loader, atom skills visualization, deep ocean theme, and ambient effects.',
    techStack: ['React', 'Vite', 'CSS'],
    link: 'https://github.com/HimanshuMahto/Portfolio',
    demoLink: null,
  },
];

export const projectsNav = [
  { name: 'all' },
  { name: 'Front-End' },
  { name: 'Android' },
  { name: 'Tools' },
  { name: 'ML' },
];
