export const projectsData = [
  {
    id: 1,
    title: 'NimbusStore',
    category: 'Backend',
    description: 'Cloudinary-style image processing service. JWT-authenticated uploads, nine composable transformations, and hash-deduplicated results so identical requests are served from disk instead of recomputed.',
    techStack: ['Java 17', 'Spring Boot', 'PostgreSQL', 'JWT'],
    link: 'https://github.com/HimanshuMahto/NimbusStore',
    demoLink: null,
  },
  {
    id: 2,
    title: 'Ricochet',
    category: 'Backend',
    description: 'A caching reverse-proxy that sits in front of any origin, forwards requests, and serves repeats straight from memory — every response tagged X-Cache: HIT or MISS.',
    techStack: ['Java 17', 'Spring Boot', 'Maven'],
    link: 'https://github.com/HimanshuMahto/Ricochet',
    demoLink: null,
  },
  {
    id: 3,
    title: 'Preview Anything',
    category: 'Tools',
    description: 'Zero-config CLI that auto-detects and previews JavaScript projects — supports Next.js, Vite, CRA, Express, and static HTML with intelligent port allocation.',
    techStack: ['TypeScript', 'Node.js', 'CLI'],
    link: 'https://github.com/HimanshuMahto/Preveiw-Anything',
    demoLink: null,
  },
  {
    id: 4,
    title: 'Kuikku',
    category: 'Tools',
    description: 'Privacy-first Chrome extension for quick note-taking and bookmarking. All data stored locally with real-time search — no server, no tracking.',
    techStack: ['JavaScript', 'Chrome API', 'HTML'],
    link: 'https://github.com/HimanshuMahto/Kuikku',
    demoLink: null,
  },
  {
    id: 5,
    title: 'Focus Nest',
    category: 'Android',
    description: 'Productivity app built with Kotlin to help users manage focus sessions, track goals, and stay organized throughout the day.',
    techStack: ['Kotlin', 'Jetpack Compose', 'Android SDK'],
    link: 'https://github.com/HimanshuMahto/Focus-Nest',
    demoLink: null,
  },
  {
    id: 6,
    title: 'Multiple Disease Predictor',
    category: 'ML',
    description: 'Fine-tuned ResNet101V2 on a chest X-ray dataset to 87.5% accuracy, then wired it into an Android prototype through a Flask REST API for real-time screening.',
    techStack: ['Python', 'TensorFlow', 'Flask', 'Android'],
    link: 'https://github.com/HimanshuMahto/Multiple-Disease-Prediction',
    demoLink: null,
  },
];
